### ISSUE TITLE
Edit for WebStore

### ISSUE THREAD

**Issue by mr-yt12** [mr-yt12/lichess-gui-use-code-example-new#32]
Some permissions (such as `debugger`) could be removed and the code edited to allow the extension to be published on WebStore.

Also there is some redundant code in the background from the time when debugger API was used, and now this is no longer needed.

Also currently the extension can be updated by fetching the files from this repository when the `Update` button is pressed (I think it works, but haven't been able to test it enough). If we upload to WebStore, this system would need to be removed, because WebStore would use another update system, and they won't accept the extension if it has any code loaded remotely. So we'll probably need to choose one, but first I think it's better to fix other issues before uploading to WebStore.

**Comment by randomguyreborn** [comment]
@Sentero-esp12 only debugger or any else?

**Comment by randomguyreborn** [comment]
@Sentero-esp12 Can you assign this to me?

**Comment by randomguyreborn** [comment]
@mr-yt12 I think this should be closed now cuz Play enhancement **extensions** are no longer allowed, and need to be added natively to lichess
